// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whitxowl/pvz.git/internal/domain"
)

// NewMockPVZStorage creates a new instance of MockPVZStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPVZStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPVZStorage {
	mock := &MockPVZStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPVZStorage is an autogenerated mock type for the PVZStorage type
type MockPVZStorage struct {
	mock.Mock
}

type MockPVZStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPVZStorage) EXPECT() *MockPVZStorage_Expecter {
	return &MockPVZStorage_Expecter{mock: &_m.Mock}
}

// CreatePVZ provides a mock function for the type MockPVZStorage
func (_mock *MockPVZStorage) CreatePVZ(ctx context.Context, pvz *domain.PVZ) error {
	ret := _mock.Called(ctx, pvz)

	if len(ret) == 0 {
		panic("no return value specified for CreatePVZ")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.PVZ) error); ok {
		r0 = returnFunc(ctx, pvz)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPVZStorage_CreatePVZ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePVZ'
type MockPVZStorage_CreatePVZ_Call struct {
	*mock.Call
}

// CreatePVZ is a helper method to define mock.On call
//   - ctx context.Context
//   - pvz *domain.PVZ
func (_e *MockPVZStorage_Expecter) CreatePVZ(ctx interface{}, pvz interface{}) *MockPVZStorage_CreatePVZ_Call {
	return &MockPVZStorage_CreatePVZ_Call{Call: _e.mock.On("CreatePVZ", ctx, pvz)}
}

func (_c *MockPVZStorage_CreatePVZ_Call) Run(run func(ctx context.Context, pvz *domain.PVZ)) *MockPVZStorage_CreatePVZ_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.PVZ
		if args[1] != nil {
			arg1 = args[1].(*domain.PVZ)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPVZStorage_CreatePVZ_Call) Return(err error) *MockPVZStorage_CreatePVZ_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPVZStorage_CreatePVZ_Call) RunAndReturn(run func(ctx context.Context, pvz *domain.PVZ) error) *MockPVZStorage_CreatePVZ_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockPVZStorage
func (_mock *MockPVZStorage) GetAll(ctx context.Context) ([]*domain.PVZ, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*domain.PVZ
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.PVZ, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.PVZ); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PVZ)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPVZStorage_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockPVZStorage_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPVZStorage_Expecter) GetAll(ctx interface{}) *MockPVZStorage_GetAll_Call {
	return &MockPVZStorage_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockPVZStorage_GetAll_Call) Run(run func(ctx context.Context)) *MockPVZStorage_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPVZStorage_GetAll_Call) Return(pVZs []*domain.PVZ, err error) *MockPVZStorage_GetAll_Call {
	_c.Call.Return(pVZs, err)
	return _c
}

func (_c *MockPVZStorage_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.PVZ, error)) *MockPVZStorage_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetPVZList provides a mock function for the type MockPVZStorage
func (_mock *MockPVZStorage) GetPVZList(ctx context.Context, page int, limit int) ([]*domain.PVZ, error) {
	ret := _mock.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPVZList")
	}

	var r0 []*domain.PVZ
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.PVZ, error)); ok {
		return returnFunc(ctx, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*domain.PVZ); ok {
		r0 = returnFunc(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PVZ)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, page, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPVZStorage_GetPVZList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPVZList'
type MockPVZStorage_GetPVZList_Call struct {
	*mock.Call
}

// GetPVZList is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
func (_e *MockPVZStorage_Expecter) GetPVZList(ctx interface{}, page interface{}, limit interface{}) *MockPVZStorage_GetPVZList_Call {
	return &MockPVZStorage_GetPVZList_Call{Call: _e.mock.On("GetPVZList", ctx, page, limit)}
}

func (_c *MockPVZStorage_GetPVZList_Call) Run(run func(ctx context.Context, page int, limit int)) *MockPVZStorage_GetPVZList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPVZStorage_GetPVZList_Call) Return(pVZs []*domain.PVZ, err error) *MockPVZStorage_GetPVZList_Call {
	_c.Call.Return(pVZs, err)
	return _c
}

func (_c *MockPVZStorage_GetPVZList_Call) RunAndReturn(run func(ctx context.Context, page int, limit int) ([]*domain.PVZ, error)) *MockPVZStorage_GetPVZList_Call {
	_c.Call.Return(run)
	return _c
}
