// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/whitxowl/pvz.git/internal/domain"
)

// NewMockReceptionStorage creates a new instance of MockReceptionStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReceptionStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReceptionStorage {
	mock := &MockReceptionStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReceptionStorage is an autogenerated mock type for the ReceptionStorage type
type MockReceptionStorage struct {
	mock.Mock
}

type MockReceptionStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReceptionStorage) EXPECT() *MockReceptionStorage_Expecter {
	return &MockReceptionStorage_Expecter{mock: &_m.Mock}
}

// DeleteLastAddedProduct provides a mock function for the type MockReceptionStorage
func (_mock *MockReceptionStorage) DeleteLastAddedProduct(ctx context.Context, pvzID string) (bool, error) {
	ret := _mock.Called(ctx, pvzID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLastAddedProduct")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, pvzID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, pvzID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, pvzID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReceptionStorage_DeleteLastAddedProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLastAddedProduct'
type MockReceptionStorage_DeleteLastAddedProduct_Call struct {
	*mock.Call
}

// DeleteLastAddedProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - pvzID string
func (_e *MockReceptionStorage_Expecter) DeleteLastAddedProduct(ctx interface{}, pvzID interface{}) *MockReceptionStorage_DeleteLastAddedProduct_Call {
	return &MockReceptionStorage_DeleteLastAddedProduct_Call{Call: _e.mock.On("DeleteLastAddedProduct", ctx, pvzID)}
}

func (_c *MockReceptionStorage_DeleteLastAddedProduct_Call) Run(run func(ctx context.Context, pvzID string)) *MockReceptionStorage_DeleteLastAddedProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReceptionStorage_DeleteLastAddedProduct_Call) Return(b bool, err error) *MockReceptionStorage_DeleteLastAddedProduct_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockReceptionStorage_DeleteLastAddedProduct_Call) RunAndReturn(run func(ctx context.Context, pvzID string) (bool, error)) *MockReceptionStorage_DeleteLastAddedProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetReceptionsByPVZIDs provides a mock function for the type MockReceptionStorage
func (_mock *MockReceptionStorage) GetReceptionsByPVZIDs(ctx context.Context, pvzIDs []string, startTime *time.Time, endTime *time.Time) (map[string][]*domain.Reception, error) {
	ret := _mock.Called(ctx, pvzIDs, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetReceptionsByPVZIDs")
	}

	var r0 map[string][]*domain.Reception
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, *time.Time, *time.Time) (map[string][]*domain.Reception, error)); ok {
		return returnFunc(ctx, pvzIDs, startTime, endTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, *time.Time, *time.Time) map[string][]*domain.Reception); ok {
		r0 = returnFunc(ctx, pvzIDs, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]*domain.Reception)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, *time.Time, *time.Time) error); ok {
		r1 = returnFunc(ctx, pvzIDs, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReceptionStorage_GetReceptionsByPVZIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReceptionsByPVZIDs'
type MockReceptionStorage_GetReceptionsByPVZIDs_Call struct {
	*mock.Call
}

// GetReceptionsByPVZIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - pvzIDs []string
//   - startTime *time.Time
//   - endTime *time.Time
func (_e *MockReceptionStorage_Expecter) GetReceptionsByPVZIDs(ctx interface{}, pvzIDs interface{}, startTime interface{}, endTime interface{}) *MockReceptionStorage_GetReceptionsByPVZIDs_Call {
	return &MockReceptionStorage_GetReceptionsByPVZIDs_Call{Call: _e.mock.On("GetReceptionsByPVZIDs", ctx, pvzIDs, startTime, endTime)}
}

func (_c *MockReceptionStorage_GetReceptionsByPVZIDs_Call) Run(run func(ctx context.Context, pvzIDs []string, startTime *time.Time, endTime *time.Time)) *MockReceptionStorage_GetReceptionsByPVZIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReceptionStorage_GetReceptionsByPVZIDs_Call) Return(stringToReceptions map[string][]*domain.Reception, err error) *MockReceptionStorage_GetReceptionsByPVZIDs_Call {
	_c.Call.Return(stringToReceptions, err)
	return _c
}

func (_c *MockReceptionStorage_GetReceptionsByPVZIDs_Call) RunAndReturn(run func(ctx context.Context, pvzIDs []string, startTime *time.Time, endTime *time.Time) (map[string][]*domain.Reception, error)) *MockReceptionStorage_GetReceptionsByPVZIDs_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatusClosed provides a mock function for the type MockReceptionStorage
func (_mock *MockReceptionStorage) SetStatusClosed(ctx context.Context, pvzID string) (*domain.Reception, error) {
	ret := _mock.Called(ctx, pvzID)

	if len(ret) == 0 {
		panic("no return value specified for SetStatusClosed")
	}

	var r0 *domain.Reception
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Reception, error)); ok {
		return returnFunc(ctx, pvzID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Reception); ok {
		r0 = returnFunc(ctx, pvzID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Reception)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, pvzID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReceptionStorage_SetStatusClosed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatusClosed'
type MockReceptionStorage_SetStatusClosed_Call struct {
	*mock.Call
}

// SetStatusClosed is a helper method to define mock.On call
//   - ctx context.Context
//   - pvzID string
func (_e *MockReceptionStorage_Expecter) SetStatusClosed(ctx interface{}, pvzID interface{}) *MockReceptionStorage_SetStatusClosed_Call {
	return &MockReceptionStorage_SetStatusClosed_Call{Call: _e.mock.On("SetStatusClosed", ctx, pvzID)}
}

func (_c *MockReceptionStorage_SetStatusClosed_Call) Run(run func(ctx context.Context, pvzID string)) *MockReceptionStorage_SetStatusClosed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReceptionStorage_SetStatusClosed_Call) Return(reception *domain.Reception, err error) *MockReceptionStorage_SetStatusClosed_Call {
	_c.Call.Return(reception, err)
	return _c
}

func (_c *MockReceptionStorage_SetStatusClosed_Call) RunAndReturn(run func(ctx context.Context, pvzID string) (*domain.Reception, error)) *MockReceptionStorage_SetStatusClosed_Call {
	_c.Call.Return(run)
	return _c
}
