// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whitxowl/pvz.git/internal/domain"
)

// NewMockAuthStorage creates a new instance of MockAuthStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthStorage {
	mock := &MockAuthStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthStorage is an autogenerated mock type for the AuthStorage type
type MockAuthStorage struct {
	mock.Mock
}

type MockAuthStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthStorage) EXPECT() *MockAuthStorage_Expecter {
	return &MockAuthStorage_Expecter{mock: &_m.Mock}
}

// RegisterUser provides a mock function for the type MockAuthStorage
func (_mock *MockAuthStorage) RegisterUser(ctx context.Context, user *domain.User) (string, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) (string, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) string); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthStorage_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockAuthStorage_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *MockAuthStorage_Expecter) RegisterUser(ctx interface{}, user interface{}) *MockAuthStorage_RegisterUser_Call {
	return &MockAuthStorage_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, user)}
}

func (_c *MockAuthStorage_RegisterUser_Call) Run(run func(ctx context.Context, user *domain.User)) *MockAuthStorage_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthStorage_RegisterUser_Call) Return(s string, err error) *MockAuthStorage_RegisterUser_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthStorage_RegisterUser_Call) RunAndReturn(run func(ctx context.Context, user *domain.User) (string, error)) *MockAuthStorage_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// User provides a mock function for the type MockAuthStorage
func (_mock *MockAuthStorage) User(ctx context.Context, email string) (*domain.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthStorage_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type MockAuthStorage_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthStorage_Expecter) User(ctx interface{}, email interface{}) *MockAuthStorage_User_Call {
	return &MockAuthStorage_User_Call{Call: _e.mock.On("User", ctx, email)}
}

func (_c *MockAuthStorage_User_Call) Run(run func(ctx context.Context, email string)) *MockAuthStorage_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthStorage_User_Call) Return(user *domain.User, err error) *MockAuthStorage_User_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthStorage_User_Call) RunAndReturn(run func(ctx context.Context, email string) (*domain.User, error)) *MockAuthStorage_User_Call {
	_c.Call.Return(run)
	return _c
}
