// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whitxowl/pvz.git/internal/domain"
)

// NewMockReceptionStorage creates a new instance of MockReceptionStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReceptionStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReceptionStorage {
	mock := &MockReceptionStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReceptionStorage is an autogenerated mock type for the ReceptionStorage type
type MockReceptionStorage struct {
	mock.Mock
}

type MockReceptionStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReceptionStorage) EXPECT() *MockReceptionStorage_Expecter {
	return &MockReceptionStorage_Expecter{mock: &_m.Mock}
}

// CreateProduct provides a mock function for the type MockReceptionStorage
func (_mock *MockReceptionStorage) CreateProduct(ctx context.Context, productType domain.Type, receptionId string) (*domain.Product, error) {
	ret := _mock.Called(ctx, productType, receptionId)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 *domain.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Type, string) (*domain.Product, error)); ok {
		return returnFunc(ctx, productType, receptionId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Type, string) *domain.Product); ok {
		r0 = returnFunc(ctx, productType, receptionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Type, string) error); ok {
		r1 = returnFunc(ctx, productType, receptionId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReceptionStorage_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type MockReceptionStorage_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - productType domain.Type
//   - receptionId string
func (_e *MockReceptionStorage_Expecter) CreateProduct(ctx interface{}, productType interface{}, receptionId interface{}) *MockReceptionStorage_CreateProduct_Call {
	return &MockReceptionStorage_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, productType, receptionId)}
}

func (_c *MockReceptionStorage_CreateProduct_Call) Run(run func(ctx context.Context, productType domain.Type, receptionId string)) *MockReceptionStorage_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Type
		if args[1] != nil {
			arg1 = args[1].(domain.Type)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReceptionStorage_CreateProduct_Call) Return(product *domain.Product, err error) *MockReceptionStorage_CreateProduct_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockReceptionStorage_CreateProduct_Call) RunAndReturn(run func(ctx context.Context, productType domain.Type, receptionId string) (*domain.Product, error)) *MockReceptionStorage_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// CreateReception provides a mock function for the type MockReceptionStorage
func (_mock *MockReceptionStorage) CreateReception(ctx context.Context, pvzID string, status domain.Status) (*domain.Reception, error) {
	ret := _mock.Called(ctx, pvzID, status)

	if len(ret) == 0 {
		panic("no return value specified for CreateReception")
	}

	var r0 *domain.Reception
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.Status) (*domain.Reception, error)); ok {
		return returnFunc(ctx, pvzID, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.Status) *domain.Reception); ok {
		r0 = returnFunc(ctx, pvzID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Reception)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.Status) error); ok {
		r1 = returnFunc(ctx, pvzID, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReceptionStorage_CreateReception_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReception'
type MockReceptionStorage_CreateReception_Call struct {
	*mock.Call
}

// CreateReception is a helper method to define mock.On call
//   - ctx context.Context
//   - pvzID string
//   - status domain.Status
func (_e *MockReceptionStorage_Expecter) CreateReception(ctx interface{}, pvzID interface{}, status interface{}) *MockReceptionStorage_CreateReception_Call {
	return &MockReceptionStorage_CreateReception_Call{Call: _e.mock.On("CreateReception", ctx, pvzID, status)}
}

func (_c *MockReceptionStorage_CreateReception_Call) Run(run func(ctx context.Context, pvzID string, status domain.Status)) *MockReceptionStorage_CreateReception_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.Status
		if args[2] != nil {
			arg2 = args[2].(domain.Status)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReceptionStorage_CreateReception_Call) Return(reception *domain.Reception, err error) *MockReceptionStorage_CreateReception_Call {
	_c.Call.Return(reception, err)
	return _c
}

func (_c *MockReceptionStorage_CreateReception_Call) RunAndReturn(run func(ctx context.Context, pvzID string, status domain.Status) (*domain.Reception, error)) *MockReceptionStorage_CreateReception_Call {
	_c.Call.Return(run)
	return _c
}

// GetReceptionInProgressID provides a mock function for the type MockReceptionStorage
func (_mock *MockReceptionStorage) GetReceptionInProgressID(ctx context.Context, pvzID string) (string, error) {
	ret := _mock.Called(ctx, pvzID)

	if len(ret) == 0 {
		panic("no return value specified for GetReceptionInProgressID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, pvzID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, pvzID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, pvzID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReceptionStorage_GetReceptionInProgressID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReceptionInProgressID'
type MockReceptionStorage_GetReceptionInProgressID_Call struct {
	*mock.Call
}

// GetReceptionInProgressID is a helper method to define mock.On call
//   - ctx context.Context
//   - pvzID string
func (_e *MockReceptionStorage_Expecter) GetReceptionInProgressID(ctx interface{}, pvzID interface{}) *MockReceptionStorage_GetReceptionInProgressID_Call {
	return &MockReceptionStorage_GetReceptionInProgressID_Call{Call: _e.mock.On("GetReceptionInProgressID", ctx, pvzID)}
}

func (_c *MockReceptionStorage_GetReceptionInProgressID_Call) Run(run func(ctx context.Context, pvzID string)) *MockReceptionStorage_GetReceptionInProgressID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReceptionStorage_GetReceptionInProgressID_Call) Return(s string, err error) *MockReceptionStorage_GetReceptionInProgressID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockReceptionStorage_GetReceptionInProgressID_Call) RunAndReturn(run func(ctx context.Context, pvzID string) (string, error)) *MockReceptionStorage_GetReceptionInProgressID_Call {
	_c.Call.Return(run)
	return _c
}
